language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash -ex .travis-docker.sh
services:
  - docker
sudo: false
env:
 global:
   - EXTRA_REMOTES="https://github.com/mirage/mirage-dev.git"
   - PACKAGE="vhd-format"
 matrix:
   - DISTRO=debian-stable OCAML_VERSION=4.04.2
   - DISTRO=ubuntu-16.04 OCAML_VERSION=4.03.0
   - DISTRO=centos-7 OCAML_VERSION=4.04.2
   - DISTRO=fedora-24 OCAML_VERSION=4.04.2
   - DISTRO=alpine OCAML_VERSION=4.03.0
